// Generated by Selenium IDE
// Modified to conform to Jest instead of Mocha
const webdriver = require('selenium-webdriver')
const { By } = require('selenium-webdriver')
const { until } = require('selenium-webdriver')
const chrome = require('selenium-webdriver/chrome')
const chromedriver = require('chromedriver')
const assert = require('assert')

chrome.setDefaultService(new chrome.ServiceBuilder(chromedriver.path).build())

describe('RegistrationTest', () => {
  let driver
  let vars
  beforeEach(async () => {
    driver = await new webdriver.Builder()
    .forBrowser('chrome')
    .setChromeOptions(
      new chrome.Options().addArguments([
        '--headless',
        '--no-sandbox',
        '--disable-dev-shm-usage',
      ]),
    )
    .build()
    vars = {}
  })
  afterEach(async () => {
    await driver.quit();
  })
  it('RegistrationTest', async () => {
    await driver.get("https://bikerr.herokuapp.com/auth/login")
    await driver.manage().window().setRect(1096, 675)
    await driver.findElement(By.css(".text-light > small")).click()
    await driver.findElement(By.name("name")).click()
    await driver.findElement(By.name("name")).sendKeys("Name")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("Email")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("Password")
    await driver.findElement(By.name("password2")).click()
    await driver.findElement(By.name("password2")).sendKeys("Password")
    await driver.findElement(By.css(".custom-control-label")).click()
    await driver.findElement(By.css(".mt-4")).click()
    await driver.close()
  })
})