matrix:
  include:
    -language: node_js
     node_js:
      - "stable"
     addons: 
      chrome: stable
     before_script:
      - npm install
     script:
      -npm test
    -language: react_js
      react_js:
        -"stable"
      addons:
       chrome: stable
      services:
        - mongoDB
      before_script:
        - cd client
        - npm install
      script:
       - npm test