matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      addons:
        chrome: stable
      before_script:
        - cd back-end
        - npm install
      script:
        - npm test
    - language: node_js
      node_js:
        - "stable"
      addons:
        chrome: stable
      dist: xenial
      services:
        - xvfb
        - mongodb
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 
        - cd client
        - npm install
      script:
        - npm run test
