matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      addons:
        chrome: stable
      before_script:
        - cd back-end
        - npm install
      script:
        - npm test
    - language: node_js
      node_js:
        - "stable"
      dist: xenial
      addons:
        chrome: stable
      before_install:
        - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 httpr://localhost &
      install:
        - wget -N https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - sudo mv -f ~/chromedriver /usr/local/share/
        - sudo chmod +x /usr/local/share/chromedriver
        - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
      services:
        - mongodb
        - xvfb
      before_script:
        - cd client
        - npm install
      script:
        - xvfb-run make test
