matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      addons:
        chrome: stable
      before_script:
        - cd back-end
        - npm install
      script:
        - npm test
    - language: node_js
      node_js:
        - "stable"
      addons:
        chrome: stable
      services:
        - mongodb
      before_script:
        - cd client
        - npm install
      script:
        - npm test