version: "3"
services:
  react-app:
    build: ./client 
    image: soen390team14/frontend:latest
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - erp-app
  api-server:
    build: .
    image: soen390team14/backend:latest
    ports:
      - "5000:5000"
    networks:
      - erp-app
networks:
  erp-app:
    driver: bridge